Repository fjall-rs/fjall, pull requests merged in 2025-04, with the labels that each got.

#159 Count how many compactions were performed.
  src/compaction/worker.rs
  src/keyspace.rs
  src/stats.rs
Labels: enhancement, api

#161 Count how many flushes performed by partition.
  src/flush/worker.rs
  src/partition/mod.rs
Labels: enhancement, api

#163 Improve journal recovery resilience
  src/journal/mod.rs
  src/journal/recovery.rs
  src/journal/writer.rs
  test_fixture/v2_sealed_journal_shenanigans/journals/0.sealed
  test_fixture/v2_sealed_journal_shenanigans/journals/1.sealed
  test_fixture/v2_sealed_journal_shenanigans/journals/2
  test_fixture/v2_sealed_journal_shenanigans/journals/3
  test_fixture/v2_sealed_journal_shenanigans/partitions/default/config
  test_fixture/v2_sealed_journal_shenanigans/partitions/default/levels
  test_fixture/v2_sealed_journal_shenanigans/partitions/default/manifest
  test_fixture/v2_sealed_journal_shenanigans/version
  tests/v2_sealed_journal_recovery.rs
Labels: enhancement

#160 Backgound worker RAII guards
  src/background_worker.rs
  src/compaction/worker.rs
  src/flush/worker.rs
  src/keyspace.rs
  src/lib.rs
  src/monitor.rs
  src/partition/mod.rs
  src/poison_dart.rs
  tests/partition_recover.rs
  tests/sealed_recovery.rs
Labels: enhancement, refactor, error handling
